site_name: FiveOrbs Quma
copyright: © 2022 ebene fünf GmbH
nav:
  - index.md
theme:
    name: fiveorbs
repo_url: https://github.com/fiveorbs/quma
extra:
    project: FiveOrbs Quma
plugins:
    - search
    - macros:
        module_name: docs/main
markdown_extensions:
  - admonition
