site_name: Duon Quma
copyright: © 2022 ebene fünf GmbH
nav:
  - index.md
theme:
    name: duon
repo_url: https://github.com/duon/quma
extra:
    project: Duon Quma
plugins:
    - search
    - macros:
        module_name: docs/main
markdown_extensions:
  - admonition